ecomprj/core/urls.py
from django.urls import path
from core.views import *

app_name= "core"

urlpatterns = [
     path('', index_view, name='index'),
     path('about/', about_view, name='about'),
     path('contact/', contact_view, name='contact'),
     path('propertylist/', property_list_view, name='propertylist'),
     path('faqs/', faqs_view, name='faqs'),
     path('please/', please_view, name='please'),
     path('terms&condition/', terms_view, name='terms&condition'),
     path('privacypolicy/', privacypolicy_view, name='privacypolicy'),
     
     path('Property_list/', property_list2_view, name='property-list'),
     path('Talk-To-Us/', contact2_view, name='talktous'),
     path('Dashboard/', dashboard_view, name='dashboard'),
     path('Blog/', page_view, name='page'),
     path('Manage_Account/', manageacc_view, name='manageacc'),
     path('Map/', map_view, name='map'),
     path('Blog2/', page2_view, name='page2'),
     path('Tasks/', tasks_view, name='tasks'),
     path('Cart/', cart_view, name='cart'),
     path('Advertise/', advertise_view, name='advertise'),
     
]

ecomprj/userauths/urls.py
from django.urls import path
from userauths import views
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

app_name = "userauths"

urlpatterns = [
     path("sign-up/", views.register_view, name="sign-up"),
     path("sign-in/", views.LoginView, name="sign-in"),
     path("sign-out/", views.logoutView, name="sign-out"),
     
     path('password_reset/', 
          auth_views.PasswordResetView.as_view(template_name='password_reset_form.html'), 
          name='password_reset'
          ),
     path('password_reset/done/', 
          auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), 
          name='password_reset_done'
          ),
     path('change_password/<uidb64>/<token>/', 
          auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), 
          name='password_reset_confirm'
          ),
     path('password_reset_complete/', 
          auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), 
          name='password_reset_complete'
          ),

     path('Delete_account/', views.delete_account, name='delete_account'),
     path('view_profile/', views.view_profile, name='view_profile'),
     path('Edit_profile/', views.edit_profile, name='edit_profile'),
     
     path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart_view, name='cart'),
    path('remove_from_cart/<str:item_id>/', views.remove_from_cart, name='remove_from_cart'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomprj/templates/partials/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>niHome</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">
    <link rel="icon" href="{% static 'img/icon-deal.png' %}" type="image/png">


    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>

</head>


<body>
    <div class="container-xxxl bg-white p-0">
        <!-- Spinner Start -->
        <!-- <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div> -->
        </div>
        <!-- Spinner End -->
         
         <!-- Navbar Start -->
         <div class="container-fluid nav-bar bg-transparent">
            <nav class="navbar navbar-expand-lg bg-white navbar-light py-0 px-4">
                <a href="index.html" class="navbar-brand d-flex align-items-center text-center">
                    <div class="icon p-2 me-2">
                        <img class="img-fluid" src="{% static 'img/icon-deal.png'%}" alt="Icon" style="width: 30px; height: 30px;">
                    </div>
                    <h1 class="m-0 text-primary">niHome</h1>
                </a>
                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <div class="navbar-nav ms-auto">
                        <a href="{% url 'core:index' %}" class="nav-item nav-link active">Home</a>
                        <a href="{% url 'core:about' %}" class="nav-item nav-link">About</a>
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Property</a>
                            <div class="dropdown-menu rounded-0 m-0">
                                <!-- <a href="property-type.html" class="dropdown-item">Property Type</a> -->
                                {%  if request.user.is_authenticated  %}
                                    <a href="{% url 'core:property-list' %}" class="dropdown-item">Property List</a>
                                {% else %}
                                    <a href="{% url 'core:propertylist' %}" class="dropdown-item">Property List</a>
                                {% endif %}
   
                            </div>
                        </div>                        
                        <!-- <a href="cart.html" class="nav-item nav-link">Cart</a> -->
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Help</a>
                            <div class="dropdown-menu rounded-0 m-0">
                                <a href="{% url 'core:contact' %}" class="dropdown-item">Contact</a>
                                <a href="{% url 'core:faqs' %}" class="dropdown-item">FAQs</a>
                                <a href="{% url 'core:terms&condition' %}" class="dropdown-item">Terms & Condition</a>
                                <a href="{% url 'core:privacypolicy' %}" class="dropdown-item">Privacy Policy</a>
                            </div>
                        </div>
                        {% comment %} <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="fas fa-user"></i></a>
                            <div class="dropdown-menu rounded-0 m-0">
                                {%  if request.user.is_authenticated  %}
                                <a href="{% url 'userauths:sign-out' %}" class="dropdown-item">Sign Out</a>
                                <a href="{% url 'userauths:sign-out' %}" class="btn btn-primary px-3 d-none d-lg-flex">Sign Out</a>
                                {% else %}
                                <a href="{% url 'userauths:sign-in' %}" class="dropdown-item">Sign In</a>
                                <a href="{% url 'userauths:sign-in' %}" class="btn btn-primary px-3 d-none d-lg-flex">Sign In</a>
                                {% endif %}
                            </div>
                        </div> {% endcomment %}
                    </div>
                    {% comment %} {%  if request.user.is_authenticated  %} {% endcomment %}
                        {% comment %} <a href="{% url 'userauths:sign-out' %}" class="btn btn-primary px-3 d-none d-lg-flex">Sign Out</a> {% endcomment %}
                    {% comment %} {% else %} {% endcomment %}
                        <a href="{% url 'userauths:sign-in' %}" class="btn btn-primary px-3 d-none d-lg-flex">Sign In</a>
                    {% comment %} {% endif %} {% endcomment %}
                </div>
            </nav>
        </div>
        <!-- Navbar End -->
 
        {% if messages %}
            {% for message in  messages %}
            <div class="alert alert-{{message.tags}}">
                <strong>{{message}}</strong>
            </div>
            {% endfor %}
        {% endif %}
        <script>
            setTimeout (() => {
                $(".alert").alert("close")
            }, 3000)
        </script>

        {%  block content  %}


        {%  endblock content  %}

        <!-- Footer Start -->
        <div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
            <div class="container py-5">
                <div class="row g-5">
                    <div class="col-lg-3 col-md-6">
                        <h5 class="text-white mb-4">Get In Touch</h5>
                        <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>Ongata Rongai, Kajiado, Kenya</p>
                        <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+254 792 819 977</p>
                        <p class="mb-2"><i class="fa fa-envelope me-3"></i>niHome2024@outlook.com</p>
                        <div class="d-flex pt-2">
                            <a class="btn btn-outline-light btn-social" href="https://x.com/niHome2024"><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-outline-light btn-social" href="https://www.facebook.com/profile.php?id=61564870045368&mibextid=ZbWKwL"><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-outline-light btn-social" href="https://www.instagram.com/nihome2024/?next=%2F&hl=en"><i class="fab fa-instagram"></i></a>
                            <a class="btn btn-outline-light btn-social" href="https://www.tiktok.com/@nihome80?lang=en"><i class="fab fa-tiktok"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h5 class="text-white mb-4">Quick Links</h5>
                        <a class="btn btn-link text-white-50" href="{% url 'core:about' %}">About Us</a>
                        <a class="btn btn-link text-white-50" href="{% url 'core:contact' %}">Contact Us</a>
                        <a class="btn btn-link text-white-50" href="">Our Services</a>
                        <a class="btn btn-link text-white-50" href="{% url 'core:privacypolicy' %}">Privacy Policy</a>
                        <a class="btn btn-link text-white-50" href="{% url 'core:terms&condition' %}">Terms & Condition</a>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h5 class="text-white mb-4">Photo Gallery</h5>
                        <div class="row g-2 pt-2">
                            <div class="col-4">
                                <img class="img-fluid rounded bg-light p-1" src="{% static 'img/property-4.jpg' %}" alt="">
                            </div>
                            <div class="col-4">
                                <img class="img-fluid rounded bg-light p-1" src="{% static 'img/property-1.jpg' %}" alt="">
                            </div>
                            <div class="col-4">
                                <img class="img-fluid rounded bg-light p-1" src="{% static 'img/property-1.jpg' %}" alt="">
                            </div>
                            <div class="col-4">
                                <img class="img-fluid rounded bg-light p-1" src="{% static 'img/property-5.jpg' %}" alt="">
                            </div>
                            <div class="col-4">
                                <img class="img-fluid rounded bg-light p-1" src="{% static 'img/property-3.jpg' %}" alt="">
                            </div>
                            <div class="col-4">
                                <img class="img-fluid rounded bg-light p-1" src="{% static 'img/property-6.jpg' %}" alt="">
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h5 class="text-white mb-4">Newsletter</h5>
                        <p>SignUp to our newsletter to receive email on updates and new property listings.</p>
                        <div class="position-relative mx-auto" style="max-width: 400px;" >
                            <script>
                                function saveEmail() {
                                    var email = document.getElementById('email').value;
                                    localStorage.setItem('userEmail', email);
                                }
                            </script>
                            <form action="{% url 'userauths:sign-up' %}" method="get" onsubmit="saveEmail()">
                                <input class="form-control bg-transparent w-100 py-3 ps-4 pe-5" type="email" id="email" name="email" placeholder="Your email">
                                <button type="submit" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="copyright">
                    <div class="row">
                        <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                            &copy; <a class="border-bottom" href="{% url 'core:index' %}">niHome</a>, All Right Reserved. <br/><br/>
							<p>Designed By <a class="border-bottom" href="https://htmlcodex.com/">HTML Codex</a></p>
                        </div>
                        <div class="col-md-6 text-center text-md-end">
                            <div class="footer-menu">
                                <a href="{% url 'core:index' %}">Home</a>
                                <a href="{% url 'core:faqs' %}">FAQs</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/wow/wow.min.js' %}"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main2.js' %}"></script>

    <script src="{% static 'css/assets/js/util.js' %}"></script> <!-- util functions included in the CodyHouse framework -->
    <script src="{% static 'css/assets/js/main.js' %}"></script> 
</body>

</html>

ecomprj/templates/partials/base3.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>niHome</title>
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">
    <link rel="icon" href="{% static 'img/icon-deal.png' %}" type="image/png">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
       
        .logo {
            font-size: 2em;
            font-weight: bold;
        }
        .navigation {
            margin-top: 10px;
        }
        .navigation a {
            color: #fff;
            text-decoration: none;
            margin: 0 15px;
            font-size: 1.2em;
        }
        .container2 {
            max-width: 1200px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .container2 h1 {
            margin-bottom: 20px;
        }
        .container2 p {
            margin-bottom: 20px;
            color: #555;
        }
        .blog-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 20px;
        }
        .blog-post {
            background-color: #fff;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            text-align: center;
            padding: 15px;
        }
        .blog-post img {
            width: 100%;
            height: auto;
            border-bottom: 1px solid #ddd;
        }
        .blog-post h2 {
            margin: 15px 0 10px;
        }
        .blog-post p {
            color: #555;
        }
        .btn {
            background-color: #06c760;
            color: #fff;
            padding: 10px 20px;
            text-decoration: none;
            border-radius: 5px;
            font-size: 0.9em;
            display: inline-block;
            margin-top: 10px;
        }
        .btn:hover {
            background-color: #06c760;
        }
        .btn-arrow::after {
            content: ' →';
        }
        .pagination {
            text-align: center;
            margin-top: 20px;
        }
        .pagination a {
            color: #06c760;
            text-decoration: none;
            margin: 0 10px;
            font-size: 1.2em;
        }
    </style>
</head>
<body>
    <header>
        <!-- Content Start -->
        <div class="content">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-light navbar-light sticky-top px-4 py-0">
                <a href="{% url 'core:dashboard' %}" class="nav-link">
                    <i class="fa fa-dashboard me-lg-2"></i>
                    <span class="d-none d-lg-inline-flex">Dashboard</span>
                </a>
                <div class="navbar-nav align-items-center ms-auto">
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link">
                            <i class="fa fa-envelope me-lg-2"></i>
                            <span class="d-none d-lg-inline-flex"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">
                                <div class="d-flex align-items-center">
                                    <img class="rounded-circle" src="{% static 'img/user.jpg' %}" alt="" style="width: 40px; height: 40px;">
                                    <div class="ms-2">
                                        <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                                        <small>15 minutes ago</small>
                                    </div>
                                </div>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <div class="d-flex align-items-center">
                                    <img class="rounded-circle" src="{% static 'img/user.jpg' %}" alt="" style="width: 40px; height: 40px;">
                                    <div class="ms-2">
                                        <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                                        <small>15 minutes ago</small>
                                    </div>
                                </div>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <div class="d-flex align-items-center">
                                    <img class="rounded-circle" src="{% static 'img/user.jpg' %}" alt="" style="width: 40px; height: 40px;">
                                    <div class="ms-2">
                                        <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                                        <small>15 minutes ago</small>
                                    </div>
                                </div>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item text-center">See all message</a>
                        </div>
                    </div>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link">
                            <i class="fa fa-bell me-lg-2"></i>
                            <span class="d-none d-lg-inline-flex"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">Profile updated</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">New user added</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">Password changed</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item text-center">See all notifications</a>
                        </div>
                    </div>
                    <a href="#" class="nav-link">
                        <i class="fa fa-shopping-cart"></i>
                        <span class="d-none d-lg-inline-flex"></span>
                    </a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <img class="rounded-circle me-lg-2" src="{{ user.profile.profile_picture.url }}" alt="" style="width: 40px; height: 40px;">
                            <span class="d-none d-lg-inline-flex">{{ request.user.username }}</span>
                        </a>
                        
                        <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                            <a href="{% url 'userauths:view_profile' %}" class="dropdown-item">My Profile</a>
                            <a href="#" class="dropdown-item">Settings</a>
                            <a href="{% url 'userauths:sign-out' %}" class="dropdown-item">Sign Out</a>
                        </div>
                    </div>
                </div>
            </nav>
            <!-- Navbar End -->
    </header>

        {%  block content  %}


        {%  endblock content  %}

        <!-- Footer Start -->
        <div class="container-fluid pt-4 px-4">
            <div class="bg-light rounded-top p-4">
                <div class="row">
                    <div class="col-12 col-sm-6 text-center text-sm-start">
                        &copy; <a class="border-bottom" href="{% url 'core:dashboard' %}">niHome</a>, All Right Reserved. <br/><br/>
                    </div>
                    <div class="col-12 col-sm-6 text-center text-sm-end">
                        <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                        Designed By <a href="https://htmlcodex.com">HTML Codex</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->
    </div>
    <!-- Content End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
</div>

<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'lib/chart/chart.min.js' %}"></script>
<script src="{% static 'lib/easing/easing.min.js' %}"></script>
<script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
<script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'lib/tempusdominus/js/moment.min.js' %}"></script>
<script src="{% static 'lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
<script src="{% static 'lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

<!-- Template Javascript -->
<script src="{% static 'js/main.js' %}"></script>
<!-- other Template Javascript -->
<script src="{% static 'js/main2.js' %}"></script>
</body>

</html>